package Main;


import java.awt.Toolkit;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.regex.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MR-10
 */
public class New_User extends javax.swing.JFrame {

    /**
     * Creates new form New_User
     */
    public New_User() {
        initComponents();
        check_lbl.setVisible(false);
        coress_lbl1.setVisible(false);
        cross_lbl2.setVisible(false);
        cross_lbl3.setVisible(false);
        check_lbl.setVisible(false);
        check_lbl2.setVisible(false);
        check_lbl1.setVisible(false);
        setIconImage();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Username_1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        New_password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Confirm_pass = new javax.swing.JTextField();
        Submitbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Erroruser = new javax.swing.JLabel();
        Erorrpass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ErrorConfirm = new javax.swing.JLabel();
        check_lbl = new javax.swing.JLabel();
        coress_lbl1 = new javax.swing.JLabel();
        check_lbl1 = new javax.swing.JLabel();
        check_lbl2 = new javax.swing.JLabel();
        cross_lbl2 = new javax.swing.JLabel();
        cross_lbl3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setMinimumSize(new java.awt.Dimension(800, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/6.png"))); // NOI18N
        jLabel1.setText("User Name :");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(275, 157, 180, 40);

        Username_1.setPreferredSize(new java.awt.Dimension(59, 30));
        Username_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_1ActionPerformed(evt);
            }
        });
        Username_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Username_1KeyReleased(evt);
            }
        });
        getContentPane().add(Username_1);
        Username_1.setBounds(275, 204, 363, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-password-30.png"))); // NOI18N
        jLabel2.setText("Password :");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(276, 297, 180, 39);

        New_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_passwordActionPerformed(evt);
            }
        });
        New_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                New_passwordKeyReleased(evt);
            }
        });
        getContentPane().add(New_password);
        New_password.setBounds(275, 362, 363, 39);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-password-30.png"))); // NOI18N
        jLabel3.setText("Confirm Password :");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(269, 443, 190, 37);

        Confirm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_passActionPerformed(evt);
            }
        });
        Confirm_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Confirm_passKeyReleased(evt);
            }
        });
        getContentPane().add(Confirm_pass);
        Confirm_pass.setBounds(269, 490, 363, 37);

        Submitbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Submitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-right-arrow-30.png"))); // NOI18N
        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Submitbtn);
        Submitbtn.setBounds(250, 633, 184, 47);

        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-left-arrow-30.png"))); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn);
        Backbtn.setBounds(555, 633, 193, 47);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 605, 1003, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 104, 1003, 13);

        Erroruser.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        Erroruser.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(Erroruser);
        Erroruser.setBounds(276, 251, 363, 18);

        Erorrpass.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        Erorrpass.setForeground(new java.awt.Color(252, 0, 0));
        Erorrpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ErorrpassKeyReleased(evt);
            }
        });
        getContentPane().add(Erorrpass);
        Erorrpass.setBounds(275, 409, 363, 18);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign logo.png"))); // NOI18N
        jLabel5.setText("New User");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 940, 98);

        ErrorConfirm.setFont(new java.awt.Font("Calibri", 3, 13)); // NOI18N
        ErrorConfirm.setForeground(new java.awt.Color(252, 0, 0));
        ErrorConfirm.setPreferredSize(new java.awt.Dimension(300, 20));
        getContentPane().add(ErrorConfirm);
        ErrorConfirm.setBounds(269, 545, 363, 20);

        check_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-mark-25.png"))); // NOI18N
        getContentPane().add(check_lbl);
        check_lbl.setBounds(643, 204, 39, 40);

        coress_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross.png"))); // NOI18N
        getContentPane().add(coress_lbl1);
        coress_lbl1.setBounds(689, 204, 39, 40);

        check_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-mark-25.png"))); // NOI18N
        getContentPane().add(check_lbl1);
        check_lbl1.setBounds(643, 362, 39, 40);

        check_lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-mark-25.png"))); // NOI18N
        getContentPane().add(check_lbl2);
        check_lbl2.setBounds(644, 487, 39, 40);

        cross_lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross.png"))); // NOI18N
        getContentPane().add(cross_lbl2);
        cross_lbl2.setBounds(689, 362, 39, 40);

        cross_lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross.png"))); // NOI18N
        getContentPane().add(cross_lbl3);
        cross_lbl3.setBounds(690, 487, 39, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/wepik-export-20231129144238CKYK.jpeg"))); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-40, 0, 990, 740);

        setSize(new java.awt.Dimension(962, 783));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Confirm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_passActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Confirm_passActionPerformed

    private void Username_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_1ActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Ragistration().setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/user","root","root");
            String sql="Insert into login(Username,Login_Password) values(?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,Username_1.getText());
            pst.setString(2,New_password.getText());
            String Login_Password=New_password.getText();
            String Confirm_Password=Confirm_pass.getText();
            
            if(!Login_Password.equals(Confirm_Password)){
             JOptionPane.showMessageDialog(this,"Incorrect Password");
             Confirm_pass.setText("");
             New_password.setText("");
             
                
            }
//            else if(Username_1.equals(null)){
//                JOptionPane.showMessageDialog(this, "Enter username");
//                
//            }
//            else if(New_password.equals(null)){
//                JOptionPane.showMessageDialog(null, "Enter password");
//                
//            }else if(Confirm_pass.equals(null)){
//                JOptionPane.showMessageDialog(null, "Enter Confirm password");
//                
//            }
            
            else {
                
                 pst.execute();
                 JOptionPane.showMessageDialog(this,"Data Added Successfully");
                 setVisible(false);
                 new Login_Page().setVisible(true);
            }
            conn.close();
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Username Already Exited");
           
        }
        
        
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void Username_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Username_1KeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{6,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Username_1.getText());
        if(!match.matches()){
            Erroruser.setText("At Least 6 Charactors or Numbers");
            coress_lbl1.setVisible(true);
            check_lbl.setVisible(false);
        }
        
        else{
            Erroruser.setText(null);
           check_lbl.setVisible(true);
            coress_lbl1.setVisible(false);
        }
        
                
    }//GEN-LAST:event_Username_1KeyReleased

    private void New_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_passwordActionPerformed
        // TODO add your handling code here:
        
//        String PATTERN="^[a-zA-Z0-9]{8,20}$";
//        Pattern patt=Pattern.compile(PATTERN);
//        Matcher match=patt.matcher(New_password.getText());
//        if(!match.matches()){
//            Errorpass.setText("At Least 8 Characters & Numbers");
//        }
//        else{
//            Errorpass.setText(null);

    }//GEN-LAST:event_New_passwordActionPerformed

    private void ErorrpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErorrpassKeyReleased
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_ErorrpassKeyReleased

    private void New_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_New_passwordKeyReleased
        // TODO add your handling code here:
         String PATTERN1="^[a-zA-Z0-9]{8,20}$";
        Pattern patt=Pattern.compile(PATTERN1);
        Matcher match=patt.matcher(New_password.getText());
        if(!match.matches()){
            Erorrpass.setText("At Least 8 Characters or Numbers");
            cross_lbl2.setVisible(true);
            check_lbl1.setVisible(false);
        }
        else{
            Erorrpass.setText(null);
            check_lbl1.setVisible(true);
            cross_lbl2.setVisible(false);
    }  
    }//GEN-LAST:event_New_passwordKeyReleased

    private void Confirm_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Confirm_passKeyReleased
        // TODO add your handling code here:
        String PATTERN1=New_password.getText();
        Pattern patt=Pattern.compile(PATTERN1);
        Matcher match=patt.matcher(Confirm_pass.getText());
        if(!match.matches()){
            ErrorConfirm.setText("Password Not Match");
            cross_lbl3.setVisible(true);
            check_lbl2.setVisible(false);
        }
        else{
            ErrorConfirm.setText(null);
             check_lbl2.setVisible(true);
            cross_lbl3.setVisible(false);
    }  
    }//GEN-LAST:event_Confirm_passKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Confirm_pass;
    private javax.swing.JLabel Erorrpass;
    private javax.swing.JLabel ErrorConfirm;
    private javax.swing.JLabel Erroruser;
    private javax.swing.JTextField New_password;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JTextField Username_1;
    private javax.swing.JLabel check_lbl;
    private javax.swing.JLabel check_lbl1;
    private javax.swing.JLabel check_lbl2;
    private javax.swing.JLabel coress_lbl1;
    private javax.swing.JLabel cross_lbl2;
    private javax.swing.JLabel cross_lbl3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("id-card.png")));
    }


}
