package Main;


import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author MR-18
 */
public class Ragistration extends javax.swing.JFrame {

     public String ContactPattern="[789]{1}[0-9]{9}+";
     public String EmailPattern= "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
  
   
    
    
    /**
     * Creates new form StudentDetails
     */
    public Ragistration() {
        initComponents();
        setIconImage();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        check1.setVisible(false);
        lbl_Check.setVisible(false);
        cross1.setVisible(false);
        Cross.setVisible(false);
       // setLocation(size.width/2 getwidth()/2,size.height/2,getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Student = new javax.swing.JLabel();
        Std_Name = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        lblphoto = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Address = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Dob = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        Courses = new javax.swing.JComboBox<>();
        Dob1 = new com.toedter.calendar.JDateChooser();
        choosebtn = new javax.swing.JButton();
        Cross = new javax.swing.JLabel();
        cross1 = new javax.swing.JLabel();
        check1 = new javax.swing.JLabel();
        lbl_Check = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-id-35.png"))); // NOI18N
        jLabel1.setText("Student Registration Form");
        jLabel1.setIconTextGap(15);
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 45));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1396, 60));

        Student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Std-icon.png"))); // NOI18N
        Student.setText("Student Name : ");
        Student.setPreferredSize(new java.awt.Dimension(92, 37));
        getContentPane().add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 133, 260, -1));

        Std_Name.setPreferredSize(new java.awt.Dimension(165, 30));
        getContentPane().add(Std_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 134, 401, 37));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/email-icon.png"))); // NOI18N
        email.setText("Email_Id : ");
        email.setPreferredSize(new java.awt.Dimension(172, 37));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 209, 260, -1));

        Email.setPreferredSize(new java.awt.Dimension(165, 30));
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailKeyReleased(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 210, 401, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-phone-number-20.png"))); // NOI18N
        jLabel4.setText("Contact_No :");
        jLabel4.setPreferredSize(new java.awt.Dimension(92, 37));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 285, 262, -1));

        Contact.setPreferredSize(new java.awt.Dimension(165, 30));
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactKeyReleased(evt);
            }
        });
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 286, 401, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gender-icon.png"))); // NOI18N
        jLabel5.setText("Gender : ");
        jLabel5.setPreferredSize(new java.awt.Dimension(92, 37));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 363, 262, -1));

        male.setBackground(new java.awt.Color(204, 255, 255));
        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setText("Male");
        male.setPreferredSize(new java.awt.Dimension(70, 25));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 364, 112, 36));

        Female.setBackground(new java.awt.Color(204, 255, 255));
        Female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Female.setText("Female");
        Female.setPreferredSize(new java.awt.Dimension(70, 25));
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 363, 87, 37));

        lblphoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto.png"))); // NOI18N
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblphoto.setPreferredSize(new java.awt.Dimension(92, 25));
        getContentPane().add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 89, 180, 222));

        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Submit.png"))); // NOI18N
        Submit.setText("Next");
        Submit.setPreferredSize(new java.awt.Dimension(125, 25));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 710, 182, 55));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/address-20.png"))); // NOI18N
        jLabel10.setText("Address :");
        jLabel10.setPreferredSize(new java.awt.Dimension(92, 37));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 440, 262, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 1396, 15));

        Address.setPreferredSize(new java.awt.Dimension(165, 30));
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 441, 401, 37));

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/5.png"))); // NOI18N
        reset.setText("Reset");
        reset.setIconTextGap(6);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 710, 165, 55));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/female-20.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 37));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 363, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/male-icon.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(33, 37));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 364, 27, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 671, 1396, 11));

        Dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-birthday-date-30.png"))); // NOI18N
        Dob.setText("Date Of Brith : ");
        getContentPane().add(Dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 516, 262, 37));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-courses-25.png"))); // NOI18N
        jLabel8.setText("Courses : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 590, 262, 36));

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-left-arrow-30.png"))); // NOI18N
        logout.setText("Back");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 710, 161, 54));

        Courses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Stream", "Engineering", "BSc", "BCA", "B. Pharmacy", "B.Com", "Law", "BA", " ", " " }));
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });
        getContentPane().add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 401, 36));
        getContentPane().add(Dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 516, 401, 37));

        choosebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        choosebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-upload-20.png"))); // NOI18N
        choosebtn.setText("Upload");
        choosebtn.setPreferredSize(new java.awt.Dimension(125, 25));
        choosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(choosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 349, 142, 36));

        Cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross.png"))); // NOI18N
        getContentPane().add(Cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 210, 43, 37));

        cross1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross.png"))); // NOI18N
        getContentPane().add(cross1, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 286, 43, 37));

        check1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-mark-25.png"))); // NOI18N
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 286, 43, 37));

        lbl_Check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-mark-25.png"))); // NOI18N
        getContentPane().add(lbl_Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 209, 43, 38));

        Error.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 390, 20));

        Error1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Error1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 390, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgdemo.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/user","root","root");
            String sql="insert into std_info"
                    +"(Student_Name,Email_ID,Contact,Gender,"
                    +"Address,Date_Of_Brith,courses,"
                    +"std_photo) values(?,?,?,?,?,?,?,?)";
           
            PreparedStatement pst=conn.prepareStatement(sql);
            String Std_Name1=(String)Std_Name.getText();
            pst.setString(1, Std_Name1);
            String Email_Id=(String)Email.getText();   
            pst.setString(2, Email_Id);
            String Mobile_Number=(String)Contact.getText();         
            pst.setString(3, Mobile_Number);
            
            pst.setString(4, Gender);
            String Address1=(String)Address.getText();
            pst.setString(5, Address1);
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
            String date=sdf.format(Dob1.getDate());
            pst.setString(6, date);
            String courses=(String) Courses.getSelectedItem();
            pst.setString(7, courses);
            pst.setBytes(8, person_image);
             if(!Email_Id.matches(EmailPattern) ){
                 JOptionPane.showMessageDialog(this, "Invalid Email Id");
                 Email.setText(""); 
             }
            
             else if(!Mobile_Number.matches(ContactPattern)){
                 JOptionPane.showMessageDialog(this ,"Invalid Number");
                Contact.setText(""); 
             }
//             else if(!Address1.equals(null)){
//                 JOptionPane.showMessageDialog(this,"Address Requried");
//                 Address.setText("");
//             }
//             else if(!date.equals(null)){
//                 JOptionPane.showMessageDialog(this,"Date Of Brith Mandatory");
//                 Dob1.setDate(null);
//             }
//             else if(!Gender.equals(null)){
//                 JOptionPane.showMessageDialog(this,"Select One Option");
//                 
//             }
//             else if(!courses.equals(null)){
//                 JOptionPane.showMessageDialog(this,"select Your Courses");
//                 Courses.setSelectedItem(null);
//                 
//             }
//             else if(!Std_Name1.equals("")){
//                 JOptionPane.showMessageDialog(this,"Name Mandatory");
//                 Std_Name.setText("");
//             }
//             else if(!person_image.equals(null)){
//                 JOptionPane.showConfirmDialog(this,"Upload Your Photo");
//                 lblphoto.setIcon(null);
//             }
             else{
            pst.execute();
             int b=JOptionPane.showConfirmDialog(null,"Data Save successfully","select",JOptionPane.YES_NO_OPTION);
        if(b==0){
            dispose();
            new New_User().setVisible(true);
                }
             }
          conn.close();
         }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Fill All Details ......");
            System.out.println(e);
                               }
        
//        finally{
//            try{
//                rs.close();
//                
//            }
//            catch(Exception e){
//                JOptionPane.showMessageDialog(null, e);
//            }
//        }
    }//GEN-LAST:event_SubmitActionPerformed

      
    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
        
        Gender="Female";
        Female.setSelected(true);
        male.setSelected(false);
       
    }//GEN-LAST:event_FemaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        Gender="Male";
        male.setSelected(true);
        Female.setSelected(false);
        
    }//GEN-LAST:event_maleActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        Std_Name.setText("");
        Email.setText("");
        Contact.setText("");
        if(male.isSelected()){
            male.setSelected(false);
        }
        else{
            Female.setSelected(false);
        }
        Address.setText("");
        Courses.setSelectedItem(" ");
        lblphoto.setIcon(null);
        Dob1.setDate(null);
        Courses.setSelectedItem(null);
        
        
        
           
//        }
    }//GEN-LAST:event_resetActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_ContactActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
//       
      int a= JOptionPane.showConfirmDialog(null,"Do You Want to Back the Registration","select",JOptionPane.YES_NO_OPTION);
      if(a==0){
            dispose();
          new Login_Page().setVisible(true);
      }
//   
    }//GEN-LAST:event_logoutActionPerformed

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CoursesActionPerformed

    private void choosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosebtnActionPerformed
        // TODO add your handling code here:
                JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        filename= f.getAbsolutePath();
        ImageIcon imageicon =new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH));
        lblphoto.setIcon(imageicon);
        try { 
            File image=new File(filename);
            FileInputStream fix=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            
            
            for(int number;(number = fix.read(buf)) != -1;){
                bos.write(buf,0,number);
                
            }
            person_image =bos.toByteArray();
                  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_choosebtnActionPerformed

    private void EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyReleased
        // TODO add your handling code here:
        
         Pattern patt=Pattern.compile(EmailPattern);
        Matcher match=patt.matcher(Email.getText());
        if(!match.matches()){
           Cross.setVisible(true);
           lbl_Check.setVisible(false);
           Error1.setText("Invalied Email ID");
        }
        else{
            Cross.setVisible(false);
            lbl_Check.setVisible(true);
         Error1.setText(null);
        }
    }//GEN-LAST:event_EmailKeyReleased

    private void ContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactKeyReleased
        // TODO add your handling code here:
          Pattern patt=Pattern.compile(ContactPattern);
        Matcher match=patt.matcher(Contact.getText());
        if(!match.matches()){
           cross1.setVisible(true);
           check1.setVisible(false);
           
           Error.setText("Invailed Contact Number");
        }
        else{
            cross1.setVisible(false);
           check1.setVisible(true);
           Error.setText(null);
        }
    }//GEN-LAST:event_ContactKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ragistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ragistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ragistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ragistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ragistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Contact;
    private javax.swing.JComboBox<String> Courses;
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel Dob;
    private com.toedter.calendar.JDateChooser Dob1;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel Error1;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField Std_Name;
    private javax.swing.JLabel Student;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel check1;
    private javax.swing.JButton choosebtn;
    private javax.swing.JLabel cross1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Check;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
    
    private void setIconImage() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("id-card.png")));
    }
    
    private ImageIcon format=null;
    String filename=null;
    byte[] person_image=null;
    private String Gender;
   
     
   //if(!Mobile_Number.matches(ContactPattern) || Mobile_Number.length()!=10 ){
//                JOptionPane.showMessageDialog(null, "Invalid Mobile Number");
//            }
//              if(Mobile_Number.equals(""))
//             {
//                 JOptionPane.showMessageDialog(null, "Contact Number Required");
    
//             }
       //             if(!Email_Id.matches(EmailPattern)){
//                JOptionPane.showMessageDialog(null, "Invalid Email Id");
//            }
//            else if(Email_Id.equals("")){
//                JOptionPane.showMessageDialog(null, "Email Id Required");
//                
//            }


}
