package Main;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.DriverManager;
import javafx.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MR-18
 */
public class Show_ID_Card extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    
    /**
     * Creates new form Student_infomation
     */
    public Show_ID_Card() {
        initComponents();
        setIconImage();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Searchbar = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        panelid = new javax.swing.JPanel();
        colbl = new javax.swing.JLabel();
        Id_name = new javax.swing.JTextField();
        Doblbl = new javax.swing.JLabel();
        addlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        Id_dob = new javax.swing.JTextField();
        id_couses = new javax.swing.JTextField();
        id_Address = new javax.swing.JTextField();
        id_Gender = new javax.swing.JTextField();
        emaillbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Id_email = new javax.swing.JTextField();
        moblbl = new javax.swing.JLabel();
        ID_mob = new javax.swing.JTextField();
        lblphoto1 = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Infomation");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Student ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 40));

        Searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbarActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 392, 40));

        Searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-40.png"))); // NOI18N
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 40, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Check ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 120, 40));

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-left-arrow-30.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setIconTextGap(12);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 656, 269, 47));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1320, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 628, 1320, 10));

        panelid.setBackground(new java.awt.Color(255, 255, 255));
        panelid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelid.setForeground(new java.awt.Color(255, 255, 255));
        panelid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        colbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colbl.setText("Courses :");
        panelid.add(colbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 166, 162, 33));
        panelid.add(Id_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 53, 470, 39));

        Doblbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Doblbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Doblbl.setText("Date Of Brith");
        panelid.add(Doblbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 117, 162, 35));

        addlbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlbl.setText("Address");
        panelid.add(addlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 217, 162, 36));

        namelbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namelbl.setText("Name :");
        panelid.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 58, 162, 28));
        panelid.add(Id_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 115, 228, 38));
        panelid.add(id_couses, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 166, 228, 33));
        panelid.add(id_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 217, 470, 36));
        panelid.add(id_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 115, 120, 38));

        emaillbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emaillbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emaillbl.setText("Email ID:");
        panelid.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 338, 162, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gender :");
        panelid.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 115, 105, 38));
        panelid.add(Id_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 338, 413, 30));

        moblbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        moblbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        moblbl.setText("Mobile Number :");
        panelid.add(moblbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 282, 162, 33));
        panelid.add(ID_mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 282, 259, 33));

        lblphoto1.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblphoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/istockphoto.jpg"))); // NOI18N
        lblphoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblphoto1.setPreferredSize(new java.awt.Dimension(92, 25));
        panelid.add(lblphoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 201, 250));

        getContentPane().add(panelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1218, 428));

        printbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pdf-35.png"))); // NOI18N
        printbtn.setText("Print ID");
        printbtn.setIconTextGap(12);
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        getContentPane().add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 656, 264, 47));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/1245.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
        try{ Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user","root","root");
            String sql="select *from Std_info where Std_ID=?";
            
            PreparedStatement pst=con.prepareStatement(sql);
            int Std_ID=Integer.parseInt(Searchbar.getText());
            pst.setInt(1, Std_ID);
            
            
            
           ResultSet rs =pst.executeQuery();
           if(rs.next()==false){
               JOptionPane.showMessageDialog(this,"Recored Not Found");
               Id_name.setText("");
               id_Address.setText("");
               Id_dob.setText("");
               id_Gender.setText("");
               Id_email.setText("");
               id_couses.setText("");
               ID_mob.setText("");
               lblphoto1.setIcon(null);
               
               
           }
           else{
               Id_name.setText(rs.getString("Student_Name"));
               Id_dob.setText(rs.getString("Date_Of_Brith"));
               id_Gender.setText(rs.getString("Gender"));
               ID_mob.setText(rs.getString("Contact"));
               id_Address.setText(rs.getString("Address"));
               Id_email.setText(rs.getString("Email_Id"));
               id_couses.setText(rs.getString("courses"));
                  byte[]image=rs.getBytes("Std_photo");
            ImageIcon imageicon =new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(lblphoto1.getWidth(),lblphoto1.getHeight(),Image.SCALE_SMOOTH));
        lblphoto1.setIcon(imageicon);
               
           }
           
           con.close();        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            System.out.println(e.getCause());
        } 
        
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        
        
        
       int a= JOptionPane.showConfirmDialog(this, "Do You Want to Back the Registration","select",JOptionPane.YES_NO_OPTION);
       if(a==0){
           setVisible(false);
        new Student_DashBorad().setVisible(true);
       }
       
    }//GEN-LAST:event_btn_backActionPerformed

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
          printPanel();
    }//GEN-LAST:event_printbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new GenrerateID().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_ID_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_ID_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_ID_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_ID_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_ID_Card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doblbl;
    private javax.swing.JTextField ID_mob;
    private javax.swing.JTextField Id_dob;
    private javax.swing.JTextField Id_email;
    private javax.swing.JTextField Id_name;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JLabel addlbl;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel colbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField id_Address;
    private javax.swing.JTextField id_Gender;
    private javax.swing.JTextField id_couses;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblphoto1;
    private javax.swing.JLabel moblbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPanel panelid;
    private javax.swing.JButton printbtn;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("id-card.png")));
    }
    
   
     private void printPanel() {
        java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
        job.setJobName("Print Panel");

        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) g;
                g2.translate(pf.getImageableX(), pf.getImageableY());

                // Your scaling logic if needed
                double scaleX = pf.getImageableWidth() / panelid.getWidth();
                double scaleY = pf.getImageableHeight() / panelid.getHeight();
                g2.scale(scaleX, scaleY);

                // Paint the panel onto the printer graphics
                panelid.print(g2);

                return Printable.PAGE_EXISTS;
            }
        });

        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
                JOptionPane.showMessageDialog(null, "Printed Sucessfully");
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(this, "Error during printing: " + ex.getMessage());
            }
        }
    }


    
}
